HomeSet.Web/Controllers/CategoriaController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using HomeSet.Models;
using HomeSet.Negocio;
using HomeSet.Domain.Dto;
using HomeSet.Domain.Entidades;
using HomeSet.Domain;
using HomeSet.Domain.Atributos;
using System.Collections.Generic;
using System.Linq;
using System;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Globalization;
using Microsoft.AspNetCore.Authorization;

namespace HomeSet.Controllers
{
    [Authorize]
    public class CategoriaController : Controller
    {
        private readonly INegocio Negocio;

        public CategoriaController(INegocio negocio)
        {
            Negocio = negocio;
        }

        //[ValidateAntiForgeryToken]
        [AjaxOnly]
        [ActionName("Listar")]
        public ActionResult Listar(string filtro, int pagina = 1, string ordenarPor = "Id", DirOrden dirOrden = DirOrden.Asc)
        {
            return View("Listar", ListQuery(filtro, pagina, ordenarPor, dirOrden));
        }

        [HttpGet]
        public IActionResult Index(string sortOrder, string searchString)
        {
            return View(ListQuery("", 1, "Id", DirOrden.Asc));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Crear(CategoriaDto dto)
        {
            if (ModelState.IsValid)
            {
                var resultado = Negocio.AltaCategoria(dto);
                if (!resultado.HayErrores)
                {
                    return new AjaxEditSuccessResult();
                }
                ModelState.AgregarErrores(resultado);
            }
            return View(dto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Modificar(CategoriaDto dto)
        {
            if (ModelState.IsValid)
            {
                var resultado = Negocio.ModificarCategoria(dto);
                if (!resultado.HayErrores)
                {
                    return new AjaxEditSuccessResult();
                }
                ModelState.AgregarErrores(resultado);
            }
            return View(dto);
        }

        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Modificar(int id)
        {
            var dto = Negocio.Obtener<Categoria, CategoriaDto>(id);
            return View(dto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Eliminar(int id)
        {
            var resultado = Negocio.EliminarCategoria(id);
            return Content(!resultado.HayErrores ? "true" : resultado.Errores.Values.First());            
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private ListaPaginada<CategoriaDto> ListQuery(string filtro, int pagina, string ordenarPor, DirOrden dirOrden)
        {
            var paginacion = new Paginacion(ordenarPor, dirOrden, pagina, 10);

            return Negocio.ListarCategoriasPaginado(filtro, paginacion);
        }
    }
}

HomeSet.Web/Controllers/CuentaController.cs
using Microsoft.AspNetCore.Mvc;
using HomeSet.Domain.Entidades;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using HomeSet.Domain.Dto;
using HomeSet.Domain;

namespace HomeSet.Controllers
{
    [Authorize]
    public class CuentaController : Controller
    {
        private readonly UserManager<Usuario> UserManager;
        private readonly SignInManager<Usuario> SignInManager;

        public CuentaController(UserManager<Usuario> userManager, SignInManager<Usuario> signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Login(string returnUrl = null)
        {
            // Clear the existing external cookie to ensure a clean login process
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginDto model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                // This doesn't count login failures towards account lockout
                // To enable password failures to trigger account lockout, set lockoutOnFailure: true
                var result = await SignInManager.PasswordSignInAsync(model.Username, model.Password, model.RememberMe, lockoutOnFailure: true);
                if (result.Succeeded)
                {
                    //_logger.LogInformation("User logged in.");
                    return RedirectToAction("Index","Home");
                }
                if (result.IsLockedOut)
                {
                    //_logger.LogWarning("User account locked out.");
                    //return RedirectToAction(nameof(Lockout));
                    return View("Lockout");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Datos inválidos");
                    return View(model);
                }
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        //[HttpGet]
        //public IActionResult Register(string returnUrl = null)
        //{
        //    ViewData["ReturnUrl"] = returnUrl;
        //    return View();
        //}

        //[HttpPost]       
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Register(UsuarioDto model, string returnUrl = null)
        //{
        //    ViewData["ReturnUrl"] = returnUrl;
        //    if (ModelState.IsValid)
        //    {
        //        var user = new Usuario { UserName = model.Username, Apellido = model.Apellido, Nombre = model.Nombre};
        //        var result = await UserManager.CreateAsync(user, model.Password);
        //        if (result.Succeeded)
        //        {
        //            //_logger.LogInformation("User created a new account with password.");

        //            //var code = await UserManager.GenerateEmailConfirmationTokenAsync(user);
        //            //var callbackUrl = Url.EmailConfirmationLink(user.Id, code, Request.Scheme);
        //            //await _emailSender.SendEmailConfirmationAsync(model.Email, callbackUrl);

        //            await SignInManager.SignInAsync(user, isPersistent: false);
        //            //_logger.LogInformation("User created a new account with password.");
        //            return RedirectToAction("Index", "Home");
        //        }
        //        AddErrors(result);
        //    }

        //    // If we got this far, something failed, redisplay form
        //    return View(model);
        //}

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await SignInManager.SignOutAsync();
            //_logger.LogInformation("User logged out.");
            return RedirectToAction("Index", "Home");
        }


        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }

    }
}

HomeSet.Web/Controllers/EventoController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using HomeSet.Models;
using HomeSet.Negocio;
using HomeSet.Domain.Dto;
using HomeSet.Domain.Entidades;
using HomeSet.Domain;
using HomeSet.Domain.Atributos;
using System.Collections.Generic;
using System.Linq;
using System;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Globalization;
using Microsoft.AspNetCore.Authorization;

namespace HomeSet.Controllers
{
    [Authorize]
    public class EventoController : Controller
    {
        private readonly INegocio Negocio;

        public EventoController(INegocio negocio)
        {
            Negocio = negocio;
        }

        //[ValidateAntiForgeryToken]
        [AjaxOnly]
        [ActionName("Listar")]
        public ActionResult Listar(string filtro, int pagina = 1, string ordenarPor = "Id", DirOrden dirOrden = DirOrden.Asc)
        {
            return View("Listar", ListQuery(filtro, pagina, ordenarPor, dirOrden));
        }

        [HttpGet]        
        public IActionResult Index(string sortOrder, string searchString)
        {
            //ViewData["NameSortParm"] = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            //ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
            //ViewData["CurrentFilter"] = searchString;

            
            //ViewBag.Items = new ListaPaginada<EventoDto>(eventos, 1, 10, 10);
            return View(ListQuery("", 1, "Fecha", DirOrden.Desc));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Crear(EventoDto dto)
        {
            if (ModelState.IsValid)
            {
                var resultado = Negocio.AltaEvento(dto);
                if (!resultado.HayErrores)
                {
                    return new AjaxEditSuccessResult();
                }
                ModelState.AgregarErrores(resultado);
            }
            CargarCategorias();
            return View(dto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Modificar(EventoDto dto)
        {
            if (ModelState.IsValid)
            {
                var resultado = Negocio.ModificarEvento(dto);
                if (!resultado.HayErrores)
                {
                    return new AjaxEditSuccessResult();
                }
                ModelState.AgregarErrores(resultado);
            }
            CargarCategorias();
            CargarSubCategorias(dto.CategoriaId);
            return View(dto);
        }

        [HttpGet]
        public IActionResult Crear()
        {
            var dto = new EventoDto { Fecha = DateTime.Now };
            CargarCategorias();
            return View(dto);
        }

        [HttpGet]
        public IActionResult Modificar(int id)
        {
            var dto = Negocio.Obtener<Evento, EventoDto>(id);
            CargarCategorias();
            CargarSubCategorias(dto.CategoriaId);
            return View(dto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Eliminar(int id)
        {
            var resultado = Negocio.EliminarEvento(id);
            return Content(!resultado.HayErrores ? "true" : resultado.Errores.Values.First());            
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private ListaPaginada<EventoDto> ListQuery(string filtro, int pagina, string ordenarPor, DirOrden dirOrden)
        {
            var paginacion = new Paginacion(ordenarPor, dirOrden, pagina, 10);

            return Negocio.ListarEventosPaginado(filtro, paginacion);
        }

        private void CargarCategorias()
        {
            ViewBag.Categorias = Negocio.ListarCategorias().Select(item => new SelectListItem { Value = item.Id.ToString(CultureInfo.InvariantCulture), Text = item.Descripcion }).ToList();
        }

        private void CargarSubCategorias(int categoriaId)
        {
            ViewBag.SubCategorias = Negocio.ListarSubCategoriasPorCategoriaId(categoriaId).Select(item => new SelectListItem { Value = item.Id.ToString(CultureInfo.InvariantCulture), Text = item.Descripcion }).ToList();
        }

        [HttpGet]
        public JsonResult ListarSubcategorias(int categoriaId)
        {
            var subcategorias = Negocio.ListarSubCategoriasPorCategoriaId(categoriaId);
            return Json(subcategorias.ToList());
        }
    }
}

HomeSet.Web/Controllers/RolController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using HomeSet.Models;
using HomeSet.Negocio;
using HomeSet.Domain.Dto;
using HomeSet.Domain.Entidades;
using HomeSet.Domain;
using HomeSet.Domain.Atributos;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Linq.Expressions;
using System;
using AutoMapper;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace HomeSet.Controllers
{
    [Authorize]
    public class RolController : Controller
    {
        private readonly RoleManager<Rol> RoleManager;
        private readonly IMapper Mapper;

        public RolController(RoleManager<Rol> roleManager, IMapper mapper)
        {
            RoleManager = roleManager;
            Mapper = mapper;
        }

        [AjaxOnly]
        [ActionName("Listar")]
        public ActionResult Listar(string filtro, int pagina = 1, string ordenarPor = "Id", DirOrden dirOrden = DirOrden.Asc)
        {
            return View("Listar", ListQuery(filtro, pagina, ordenarPor, dirOrden));
        }

        [HttpGet]
        public IActionResult Index(string sortOrder, string searchString)
        {
            return View(ListQuery("", 1, "Id", DirOrden.Asc));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Crear(RolDto dto)
        {
            if (ModelState.IsValid)
            {
                //if (await RoleManager.RoleExistsAsync(dto.Nombre))
                //{
                //    ModelState.AddModelError(string.Empty, "Ya existe un Rol con ese nombre");
                //    return View(dto);
                //}
                var rol = new Rol { Name = dto.Nombre };
                var resultado = await RoleManager.CreateAsync(rol);
                if (resultado.Succeeded)
                {
                    return new AjaxEditSuccessResult();
                }
                AddErrors(resultado);
            }
            return View(dto);
        }        

        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Eliminar(int id)
        {
            var rol = await RoleManager.FindByIdAsync(id.ToString());
            var resultado = await RoleManager.DeleteAsync(rol);
            return Content(!resultado.Errors.Any() ? "true" : resultado.Errors.FirstOrDefault().Description);            
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private ListaPaginada<RolDto> ListQuery(string filtro, int pagina, string ordenarPor, DirOrden dirOrden)
        {
            var paginacion = new Paginacion(ordenarPor, dirOrden, pagina, 10);
            var rolesQuery = RoleManager.Roles;

            Expression<Func<Rol, bool>> expresionFiltro = null;
            if (!string.IsNullOrEmpty(filtro))
            {
                filtro = filtro.Trim();
                expresionFiltro = x => x.Name.Contains(filtro);
            }

            if (expresionFiltro != null)
            {
                rolesQuery = rolesQuery.Where(expresionFiltro);
            }

            int itemsTotales = rolesQuery.Count();

            if (paginacion.OrdenarPor != null)
            {
                rolesQuery.OrderBy(paginacion.OrdenarPor, paginacion.DireccionOrden == DirOrden.Asc);
            }

            rolesQuery = rolesQuery.Skip((paginacion.Pagina - 1) * paginacion.ItemsPorPagina).Take(paginacion.ItemsPorPagina);
            var itemsDto = Mapper.Map<IList<RolDto>>(rolesQuery.ToList());

            return new ListaPaginada<RolDto>(itemsDto, paginacion.Pagina, paginacion.ItemsPorPagina, itemsTotales);
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }
    }
}

HomeSet.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HomeSet</title>
    @*<script src="~/lib/globalize/dist/globalize.js"></script>
        <script src="~/lib/globalize/dist/globalize/date.js"></script>
        <script src="~/lib/globalize/dist/globalize/message.js"></script>
        <script src="~/lib/globalize/dist/globalize/number.js"></script>*@
    <script type="text/javascript">
        var ajaxEditSuccess = 'ajax-edit-success';
                //Globalize.culture("es");
                //var btn = $.fn.button.noConflict(); // reverts $.fn.button to jqueryui btn
                //$.fn.btn = btn; // assigns bootstrap button functionality to $.fn.btn
    </script>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <script src="~/lib/jquery.js"></script>
        <script src="~/lib/popper.js"></script>
        <script src="~/lib/bootstrap.js"></script>
        <script src="~/lib/jquery.unobtrusive-ajax.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <script src="~/lib/jquery.min.js"></script>
        <script src="~/lib/popper.min.js"></script>
        <script src="~/lib/bootstrap.min.js"></script>
        <script src="~/lib/jquery.unobtrusive-ajax.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @*@RenderSection("Styles", required: false)*@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="container">
                <div class="navbar-header">
                    @*<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>*@
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">HomeSet</a>
                </div>
                @if (User.Identity.IsAuthenticated)
    {
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="Evento" asp-action="Index">Eventos</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="menuDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Menu
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li class="dropdown-submenu">
                                <a class="dropdown-item dropdown-toggle" href="#">ABM</a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="dropdown-item" asp-area="" asp-controller="Evento" asp-action="Index">Eventos</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="" asp-controller="Categoria" asp-action="Index">Categorías</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="" asp-controller="SubCategoria" asp-action="Index">Sub-Categorías</a>
                                    </li>
                                </ul>
                            </li>
                                    <li class="dropdown-submenu">
                                        <a class="dropdown-item dropdown-toggle" href="#">Administración</a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a class="dropdown-item" asp-area="" asp-controller="Usuario" asp-action="Index">Usuarios</a>
                                            </li>
                                            <li>
                                                <a class="dropdown-item" asp-area="" asp-controller="Rol" asp-action="Index">Roles</a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Cuenta" asp-action="Logout">Log out</a>
                </li>
            </ul>
            </div>
}

            </div>
        </nav>
    </header>

    <div class="container body-content">
        @RenderBody()
        <div id="alertaError" data-mensaje="Ocurrió un error" class="alert alert-danger alert-dismissible collapse alerta-box centro-pantalla" role="alert">
            @*<a class="close" data-dismiss="alert" aria-label="Close">×</a>*@
            <button id="alertCloseButton" type="button" class="close" aria-label="Close">×</button>
            <span></span>
            @*<span></span>*@
        </div>
        <div id="alertaInfo" class="alert alert-info alert-dismissible collapse alerta-box centro-pantalla" role="alert">
            <span>Operación Exitosa</span>
        </div>
        <div id="alertaExitosa" class="alert alert-success alert-dismissible collapse alerta-box centro-pantalla" role="alert">
            <span>Operación Exitosa</span>
        </div>
    </div>
    @RenderSection("Scripts", required: false)

    <div class="modal fade" id="modal-editar" tabindex="-1" role="dialog" aria-labelledby="Crear/Modificar" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modal-editar-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="modal-editar-body">
                </div>
                <div class="modal-footer">
                    <button id="modal-editar-cancelar" type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button id="modal-editar-guardar" type="button" class="btn btn-primary">Guardar</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modal-eliminar" tabindex="-1" role="dialog" aria-labelledby="Eliminar" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modal-eliminar-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="modal-eliminar-body" align="center">
                </div>
                <div class="modal-footer">
                    <button id="modal-eliminar-cancelar" type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button id="modal-eliminar-confirmar" type="button" class="btn btn-danger" data-href="">Confirmar</button>
                    @Html.AntiForgeryToken()
                </div>
            </div>
        </div>
    </div>

</body>
</html>