HomeSet.Web/Controllers/SubCategoriaController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using HomeSet.Models;
using HomeSet.Negocio;
using HomeSet.Domain.Dto;
using HomeSet.Domain.Entidades;
using HomeSet.Domain;
using HomeSet.Domain.Atributos;
using System.Collections.Generic;
using System.Linq;
using System;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Globalization;
using Microsoft.AspNetCore.Authorization;

namespace HomeSet.Controllers
{
    [Authorize]
    public class SubCategoriaController : Controller
    {
        private readonly INegocio Negocio;

        public SubCategoriaController(INegocio negocio)
        {
            Negocio = negocio;
        }

        [AjaxOnly]
        [ActionName("Listar")]
        public ActionResult Listar(string filtro, int pagina = 1, string ordenarPor = "Id", DirOrden dirOrden = DirOrden.Asc)
        {
            return View("Listar", ListQuery(filtro, pagina, ordenarPor, dirOrden));
        }

        [HttpGet]
        public IActionResult Index(string sortOrder, string searchString)
        {
            return View(ListQuery("", 1, "Id", DirOrden.Asc));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Crear(SubCategoriaDto dto)
        {
            if (ModelState.IsValid)
            {
                var resultado = Negocio.AltaSubCategoria(dto);
                if (!resultado.HayErrores)
                {
                    return new AjaxEditSuccessResult();
                }
                ModelState.AgregarErrores(resultado);
            }
            CargarCategorias();
            return View(dto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Modificar(SubCategoriaDto dto)
        {
            if (ModelState.IsValid)
            {
                var resultado = Negocio.ModificarSubCategoria(dto);
                if (!resultado.HayErrores)
                {
                    return new AjaxEditSuccessResult();
                }
                ModelState.AgregarErrores(resultado);
            }
            CargarCategorias();
            return View(dto);
        }

        [HttpGet]
        public IActionResult Crear()
        {
            //var dto = new EventoDto { Fecha = DateTime.Now };
            CargarCategorias();
            return View();
        }

        [HttpGet]
        public IActionResult Modificar(int id)
        {
            var dto = Negocio.Obtener<SubCategoria, SubCategoriaDto>(id);
            CargarCategorias();
            return View(dto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Eliminar(int id)
        {
            var resultado = Negocio.EliminarSubCategoria(id);
            return Content(!resultado.HayErrores ? "true" : resultado.Errores.Values.First());            
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private ListaPaginada<SubCategoriaDto> ListQuery(string filtro, int pagina, string ordenarPor, DirOrden dirOrden)
        {
            var paginacion = new Paginacion(ordenarPor, dirOrden, pagina, 10);

            return Negocio.ListarSubCategoriasPaginado(filtro, paginacion);
        }

        private void CargarCategorias()
        {
            ViewBag.Categorias = Negocio.ListarCategorias().Select(item => new SelectListItem { Value = item.Id.ToString(CultureInfo.InvariantCulture), Text = item.Descripcion }).ToList();
        }
    }
}

HomeSet.Web/Views/SubCategoria/Crear.cshtml
@model SubCategoriaDto
@{
    Layout = null;
    ViewData["Title"] = "Nueva Sub-Categoría";
}
@*@section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    }*@
<script src="~/lib/jquery.validate.min.js"></script>
<script src="~/lib/jquery.validate.unobtrusive.js"></script>
<script src="~/lib/messages_es_AR.min.js"></script>
<form asp-controller="SubCategoria" asp-action="Crear"
      data-ajax="true"
      data-ajax-method="POST">
    @await Html.PartialAsync("_CrearModificar", Model)

</form>

HomeSet.Web/Views/SubCategoria/Index.cshtml
@{
    ViewData["Title"] = "Sub-Categorías";
}
<div id="main" class="">
    <div class="row">
        <form id = "search-form" asp-controller="SubCategoria" asp-action="Listar"
              data-ajax="true"
              data-ajax-method="GET"
              data-ajax-mode="replace"
              data-ajax-update="#gridTabla">
            <div class="form-inline mb-2">
                <label class="control-label mb-2 mr-sm-2 mb-sm-0" for="">Filtro</label>
                <div class="mb-2 mr-sm-2 mb-sm-0">
                    <input type="text" class="form-control" id="filtro" name="filtro" placeholder="">
                </div>
                <div class="mb-2 mr-sm-2 mb-sm-0">
                    <button class="btn btn-primary" type="submit">Filtrar</button>
                </div>

            </div>
        </form>
        <div class="offset-lg-6">
            <a class="btn btn-primary" data-toggle="modal" data-target="#modal-editar" data-href=@Url.Action("Crear","SubCategoria") data-titulo="Crear Sub-Categoría">Crear Sub-Categoría</a>
        </div>
    </div>
    <div id="gridTabla" data-grid-url="@Url.Action("Listar","SubCategoria")">
        @await Html.PartialAsync("Listar", ViewData)
    </div>

</div>

HomeSet.Web/Views/SubCategoria/Listar.cshtml
@{
    Layout = null;
}
@model HomeSet.Domain.ListaPaginada<SubCategoriaDto>

<div>
    <table class="table table-sm table-responsive-sm table-striped table-bordered table-hover">
        <thead class="thead-dark">
            <tr>
                @*<th><a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]">@Html.DisplayName("Descripcion")</a></th>*@
                <th>Descripción</th>
                <th>Categoría</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Descripcion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CategoriaDescripcion)
                    </td>
                    <td align="center">
                        <a data-toggle="modal" data-target="#modal-editar" data-href=@Url.Action("Modificar","SubCategoria",new {id = @item.Id}) data-titulo="Modificar Sub-Categoría"><octicon symbol="Pencil"></octicon></a>
                    </td>
                    <td align="center">
                        <a data-toggle="modal" data-target="#modal-eliminar" data-href=@Url.Action("Eliminar","SubCategoria",new {id = @item.Id}) data-titulo="Eliminar Sub-Categoría"><octicon symbol="Trashcan"></octicon></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<nav class="" aria-label="Page navigation">
    <ul class="pagination">
        @{
            for (int i = 1; i <= Model.PaginasTotales; i++)
            {
                <li class="page-item"><a class="page-link paginador" asp-controller="SubCategoria" asp-action="Listar" asp-route-filtro="" asp-route-pagina="@i" 
              data-ajax="true"
              data-ajax-method="GET"
              data-ajax-mode="replace"
              data-ajax-update="#gridTabla">@i</a></li>
            }
        }
    </ul>
    </nav>

HomeSet.Web/Views/SubCategoria/Modificar.cshtml
@model SubCategoriaDto
@{
    Layout = null;
    ViewData["Title"] = "Modificar Sub-Categoría";
}
@Html.Hidden("Modificando", true)
<script src="~/lib/jquery.validate.min.js"></script>
<script src="~/lib/jquery.validate.unobtrusive.js"></script>
<script src="~/lib/messages_es_AR.min.js"></script>
<form asp-controller="SubCategoria" asp-action="Modificar"
      data-ajax="true"
      data-ajax-method="POST">
    @await Html.PartialAsync("_CrearModificar", Model)

</form>

HomeSet.Web/Views/SubCategoria/_CrearModificar.cshtml
@model SubCategoriaDto
@{
    var Categorias = (IEnumerable<SelectListItem>)ViewBag.Categorias;
}
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<div class="form-group">
    <label class="col-sm-2 control-label" asp-for="Descripcion"></label>
    <div class="col-sm-11">
        <input asp-for="Descripcion" class="form-control">
        <span asp-validation-for="Descripcion" class="text-danger"></span>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label" asp-for="CategoriaDescripcion"></label>
    <div class="col-sm-6">
        <select asp-for="CategoriaId" asp-items="Categorias" class="form-control" id="categoria-dropdown">
            <option disabled selected>Elegir...</option>
        </select>
        <span asp-validation-for="CategoriaId" class="text-danger"></span>
    </div>
</div>